#!/usr/bin/env bash
#retrieve the ip_address from args so it's gonna be the argument 1 and then we check if it is null we print error msg otherwise ping the ip_address 5 times
ipaddress=$1
if [ -z "$ipaddress" ]
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping -c 5 "$ipaddress"
fi
